# -*- coding: utf-8 -*-
"""
Created on Tue Jul 25 08:46:30 2017
Plot original signal and filtered signal generated by ASF dsp library
@author: JFan
"""
from pylab import plot, show, title, subplot, subplots_adjust
from os import listdir

def generateFile(filename):
    ints = []
    with open(filename) as f:
       data = [line.strip().split() for line in f.readlines()]
    for record in data:
        ints.append(int(record[1]))
    f.close()
    return ints

signalType = input('Enter the type of signal:')
inputfiles = dict()
outputfiles = dict()

directory = 'C:\\Users\\jfan\\workspace\\digitalFilter\\signalprocess\\' + signalType + '\\'
files = [f for f in listdir(directory)]
for file in files:
    date = file.split('_')
    if 'input' in date[1]:
        inputfiles[date[0]] = file
    elif 'output' in date[1]:
        outputfiles[date[0]] = file

for key in inputfiles.keys():
    inputs = generateFile(directory + inputfiles[key])
    outputs = generateFile(directory + outputfiles[key])
    if 'high' in signalType:
        plot(inputs)
        plot(outputs)
        title('Digital Filter(%s)' %(key))
        show()
    elif 'low' in signalType:
        subplot(2,1,1)
        title('Digital Filter(%s)' %(key))
        plot(range(2048), inputs, '-.')
        subplot(2,1,2)
        plot(range(256), outputs, '-.')
        subplots_adjust(hspace=.5)
        show()
